# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: 'Default'

parameters:
  - name: SCRIPRT_KEY_VAL2
    displayName: 'Select Script Key'
    type: string
    default: 'test_demo_ui_cr_hl_api_novisual'
    values: 
      - test_demo_ui_cr_hl_api_novisual
      - test_demo
      - test_demo_cr_hl

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '23.x'

- script: npm ci
  displayName: 'Install Playwright Dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: |
    set "SECRET_KEY=$(SECRET_KEY_VAL)"
    call npm run ${{ parameters.SCRIPRT_KEY_VAL2 }}
  displayName: 'Run Tests'


